#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "✅ Husky pre-commit is running (via Volta)"

echo "Node path: $(command -v node || echo 'not found')"
echo "Yarn path: $(command -v yarn || echo 'not found')"

yarn test || exit 1
